package com.openai.api.models

import com.openai.api.core.JsonString
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ListFineTunesResponseTest {

    @Test
    fun createListFineTunesResponse() {
        val listFineTunesResponse =
            ListFineTunesResponse.builder()
                .object_("string")
                .data(
                    listOf(
                        FineTune.builder()
                            .id("string")
                            .object_("string")
                            .createdAt(123L)
                            .updatedAt(123L)
                            .model("string")
                            .fineTunedModel("string")
                            .organizationId("string")
                            .status("string")
                            .hyperparams(JsonString.of("abc"))
                            .trainingFiles(
                                listOf(
                                    File.builder()
                                        .id("string")
                                        .object_("string")
                                        .bytes(123L)
                                        .createdAt(123L)
                                        .filename("string")
                                        .purpose("string")
                                        .status("string")
                                        .statusDetails(JsonString.of("abc"))
                                        .build()
                                )
                            )
                            .validationFiles(
                                listOf(
                                    File.builder()
                                        .id("string")
                                        .object_("string")
                                        .bytes(123L)
                                        .createdAt(123L)
                                        .filename("string")
                                        .purpose("string")
                                        .status("string")
                                        .statusDetails(JsonString.of("abc"))
                                        .build()
                                )
                            )
                            .resultFiles(
                                listOf(
                                    File.builder()
                                        .id("string")
                                        .object_("string")
                                        .bytes(123L)
                                        .createdAt(123L)
                                        .filename("string")
                                        .purpose("string")
                                        .status("string")
                                        .statusDetails(JsonString.of("abc"))
                                        .build()
                                )
                            )
                            .events(
                                listOf(
                                    FineTune.FineTuneEvent.builder()
                                        .object_("string")
                                        .createdAt(123L)
                                        .level("string")
                                        .message("string")
                                        .build()
                                )
                            )
                            .build()
                    )
                )
                .build()
        assertThat(listFineTunesResponse).isNotNull
        assertThat(listFineTunesResponse.object_()).isEqualTo("string")
        assertThat(listFineTunesResponse.data())
            .containsExactly(
                FineTune.builder()
                    .id("string")
                    .object_("string")
                    .createdAt(123L)
                    .updatedAt(123L)
                    .model("string")
                    .fineTunedModel("string")
                    .organizationId("string")
                    .status("string")
                    .hyperparams(JsonString.of("abc"))
                    .trainingFiles(
                        listOf(
                            File.builder()
                                .id("string")
                                .object_("string")
                                .bytes(123L)
                                .createdAt(123L)
                                .filename("string")
                                .purpose("string")
                                .status("string")
                                .statusDetails(JsonString.of("abc"))
                                .build()
                        )
                    )
                    .validationFiles(
                        listOf(
                            File.builder()
                                .id("string")
                                .object_("string")
                                .bytes(123L)
                                .createdAt(123L)
                                .filename("string")
                                .purpose("string")
                                .status("string")
                                .statusDetails(JsonString.of("abc"))
                                .build()
                        )
                    )
                    .resultFiles(
                        listOf(
                            File.builder()
                                .id("string")
                                .object_("string")
                                .bytes(123L)
                                .createdAt(123L)
                                .filename("string")
                                .purpose("string")
                                .status("string")
                                .statusDetails(JsonString.of("abc"))
                                .build()
                        )
                    )
                    .events(
                        listOf(
                            FineTune.FineTuneEvent.builder()
                                .object_("string")
                                .createdAt(123L)
                                .level("string")
                                .message("string")
                                .build()
                        )
                    )
                    .build()
            )
    }
}
