// File generated from our OpenAPI spec by Stainless.

package com.openai.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ChatCompletionChunkTest {

    @Test
    fun createChatCompletionChunk() {
        val chatCompletionChunk =
            ChatCompletionChunk.builder()
                .id("string")
                .choices(
                    listOf(
                        ChatCompletionChunk.Choice.builder()
                            .delta(
                                ChatCompletionChunk.Choice.Delta.builder()
                                    .content("string")
                                    .functionCall(
                                        ChatCompletionChunk.Choice.Delta.FunctionCall.builder()
                                            .arguments("string")
                                            .name("string")
                                            .build()
                                    )
                                    .role(ChatCompletionChunk.Choice.Delta.Role.SYSTEM)
                                    .toolCalls(
                                        listOf(
                                            ChatCompletionChunk.Choice.Delta.ToolCall.builder()
                                                .index(123L)
                                                .id("string")
                                                .function(
                                                    ChatCompletionChunk.Choice.Delta.ToolCall
                                                        .Function
                                                        .builder()
                                                        .arguments("string")
                                                        .name("string")
                                                        .build()
                                                )
                                                .type(
                                                    ChatCompletionChunk.Choice.Delta.ToolCall.Type
                                                        .FUNCTION
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .finishReason(ChatCompletionChunk.Choice.FinishReason.STOP)
                            .index(123L)
                            .logprobs(
                                ChatCompletionChunk.Choice.Logprobs.builder()
                                    .content(
                                        listOf(
                                            ChatCompletionTokenLogprob.builder()
                                                .token("string")
                                                .bytes(listOf(123L))
                                                .logprob(42.23)
                                                .topLogprobs(
                                                    listOf(
                                                        ChatCompletionTokenLogprob.TopLogprob
                                                            .builder()
                                                            .token("string")
                                                            .bytes(listOf(123L))
                                                            .logprob(42.23)
                                                            .build()
                                                    )
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .build()
                    )
                )
                .created(123L)
                .model("string")
                .object_(ChatCompletionChunk.Object.CHAT_COMPLETION_CHUNK)
                .serviceTier(ChatCompletionChunk.ServiceTier.SCALE)
                .systemFingerprint("string")
                .usage(
                    ChatCompletionChunk.Usage.builder()
                        .completionTokens(123L)
                        .promptTokens(123L)
                        .totalTokens(123L)
                        .build()
                )
                .build()
        assertThat(chatCompletionChunk).isNotNull
        assertThat(chatCompletionChunk.id()).isEqualTo("string")
        assertThat(chatCompletionChunk.choices())
            .containsExactly(
                ChatCompletionChunk.Choice.builder()
                    .delta(
                        ChatCompletionChunk.Choice.Delta.builder()
                            .content("string")
                            .functionCall(
                                ChatCompletionChunk.Choice.Delta.FunctionCall.builder()
                                    .arguments("string")
                                    .name("string")
                                    .build()
                            )
                            .role(ChatCompletionChunk.Choice.Delta.Role.SYSTEM)
                            .toolCalls(
                                listOf(
                                    ChatCompletionChunk.Choice.Delta.ToolCall.builder()
                                        .index(123L)
                                        .id("string")
                                        .function(
                                            ChatCompletionChunk.Choice.Delta.ToolCall.Function
                                                .builder()
                                                .arguments("string")
                                                .name("string")
                                                .build()
                                        )
                                        .type(
                                            ChatCompletionChunk.Choice.Delta.ToolCall.Type.FUNCTION
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                    .finishReason(ChatCompletionChunk.Choice.FinishReason.STOP)
                    .index(123L)
                    .logprobs(
                        ChatCompletionChunk.Choice.Logprobs.builder()
                            .content(
                                listOf(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("string")
                                        .bytes(listOf(123L))
                                        .logprob(42.23)
                                        .topLogprobs(
                                            listOf(
                                                ChatCompletionTokenLogprob.TopLogprob.builder()
                                                    .token("string")
                                                    .bytes(listOf(123L))
                                                    .logprob(42.23)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(chatCompletionChunk.created()).isEqualTo(123L)
        assertThat(chatCompletionChunk.model()).isEqualTo("string")
        assertThat(chatCompletionChunk.object_())
            .isEqualTo(ChatCompletionChunk.Object.CHAT_COMPLETION_CHUNK)
        assertThat(chatCompletionChunk.serviceTier())
            .contains(ChatCompletionChunk.ServiceTier.SCALE)
        assertThat(chatCompletionChunk.systemFingerprint()).contains("string")
        assertThat(chatCompletionChunk.usage())
            .contains(
                ChatCompletionChunk.Usage.builder()
                    .completionTokens(123L)
                    .promptTokens(123L)
                    .totalTokens(123L)
                    .build()
            )
    }
}
